services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        ports:
            - 3000:3000
        env_file:
            - .env.docker
        restart: always
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        env_file:
            - .env.docker
